spring:
  banner:
    location: classpath:banner.txt

logging:
  level:
    root: INFO

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:wrong-san-ip_server_identity.jks
    key-password: secret
    key-store-password: secret
    trust-store: classpath:correct_server_truststore.jks
    trust-store-password: secret
    client-auth: need